### ISSUE TITLE
Question about test process

### ISSUE THREAD

**Issue by dkssudgktpdydn** [jaggbow/magnet#3]
Dear Author,

First of all, thank you for your response last time.

I am writing to seek clarification on a specific aspect of your research. It appears to me that the proposed Magnet or MPNN methodologies require not just the PDE initial conditions as input, but also the ground truth data (PDE solutions) from the start up to a certain time window for making accurate predictions. Could you kindly confirm if my understanding is correct?

Moreover, I am keen to know if there have been attempts to conduct predictions based solely on initial conditions. I understand that in the case of Neural operator types, predictions are made for a specific time using only initial conditions. Could you elaborate on why there might be a difference in prediction methodologies between the Neural operator and the others?

Your insights will be greatly appreciated.
Kind regards,

**Comment by jaggbow** [comment]
Hi and thanks for your questions!

> I am writing to seek clarification on a specific aspect of your research. It appears to me that the proposed Magnet or MPNN methodologies require not just the PDE initial conditions as input, but also the ground truth data (PDE solutions) from the start up to a certain time window for making accurate predictions.

You are absolutely correct, we require data from existing numerical solvers so the model can learn to generalize across time but also in MAgNet's case, across space as well.

> Moreover, I am keen to know if there have been attempts to conduct predictions based solely on initial conditions. I understand that in the case of Neural operator types, predictions are made for a specific time using only initial conditions. Could you elaborate on why there might be a difference in prediction methodologies between the Neural operator and the others?

Neural operators also learn in the same way by requiring data at later time-steps as well and not only initial conditions (see Fourier Neural Operators for example). So in terms of the optimization problem at hand, it's exactly the same and we compare against FNO in the paper. However, an approach that would only use initial conditions and nothing else already exists and appeared in the [seminal paper](https://www.sciencedirect.com/science/article/abs/pii/S0021999118307125) by Raissi et. al where they're only required to match the PDE dynamics using the PDE residuals as a loss and don't require data points from a numerical solver.

So, our method and MPNN could also do the same, that is learning only from initial conditions by changing the optimization problem and instead of matching the data, we would try to reduce the PDE residual. Both approaches have their pros and cons though. If you don't know the PDE, then your only hope is to learn from the data that you have but if you do know the PDE form, then you get the advantage of not having to waste computation on a numerical solver in order to generate data and your method becomes effectively a new kind of data-driven PDE solver itself.

I hope this answers your question, let me know if you have more!

Oussama

**Comment by dkssudgktpdydn** [comment]
Dear Oussama,

Thanks to your response, I was able to gain a better understanding. Your research has greatly sparked my interest in this field. I am truly grateful for your explanation.

Best regards
